// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import LocationAutocompleteController from "./location_autocomplete_controller.js"
application.register("location-autocomplete", LocationAutocompleteController)

import MapController from "./map_controller.js"
application.register("map", MapController)
